package com.motoassembly.solution.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "Tanks")
@Getter 
@Setter 
@NoArgsConstructor
public class Tanks {
	
	@Id
    private String partId; // The ID will be automatically generated by MongoDB
    private String partNumber;
    private String assemblyStatus;
    private String statusTimestamp;

}
